'use strict';

export const GLOBAL_GET = 'GLOBAL_GET';
export const GLOBAL_SET = 'GLOBAL_SET';

export const FILTER_GET = 'FILTER_GET';
export const FILTER_SET = 'FILTER_SET';
export const FILTER_RESET ='FILTER_RESET';

export const STATUS_GET = 'STATUS_GET';
export const STATUS_SET = 'STATUS_SET';

export const ALL_ERROR_LIST = 'ALL_ERROR_LIST';
export const ARCHIVE_ERROR_LIST = 'ARCHIVE_ERROR_LIST';
export const ARCHIVE_ERROR_UPDATE = 'ARCHIVE_ERROR_UPDATE';
export const PAGE_ERROR_LIST = 'PAGE_ERROR_LIST';
export const BROWSER_ERROR_LIST = 'BROWSER_ERROR_LIST';
export const OS_ERROR_LIST = 'OS_ERROR_LIST';
export const MOST_ERROR_LIST = 'MOST_ERROR_LIST';
export const LATEST_ERROR_LIST = 'LATEST_ERROR_LIST';

export const ARCHIVE_DETAIL = 'ARCHIVE_DETAIL';
export const ARCHIVE_DETAIL_MORE = 'ARCHIVE_DETAIL_MORE';
export const ARCHIVE_UPDATE = 'ARCHIVE_UPDATE';

export const ERROR_TREND_CHART = 'ERROR_TREND_CHART';
export const ERROR_BROWSER_CHART = 'ERROR_BROWSER_CHART';
export const ERROR_OS_CHART = 'ERROR_OS_CHART';
export const ERROR_BUSINESS_CHART = 'ERROR_BUSINESS_CHART';
export const ERROR_PLATFORM_CHART = 'ERROR_PLATFORM_CHART';
